
    create table arquivo (
       id bigint generated by default as identity,
        caminho varchar(255),
        nome varchar(255),
        tamanho varchar(255),
        tipo varchar(255),
        primary key (id)
    );

    create table categoria (
       id bigint generated by default as identity,
        descricao varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table perfil (
       id bigint generated by default as identity,
        descricao varchar(255),
        primary key (id)
    );

    create table solicitacao (
       id bigint generated by default as identity,
        comentario varchar(255),
        data_solicitacao date,
        arquivo_id bigint,
        usuario_aplicante_id bigint,
        vaga_id bigint,
        primary key (id)
    );

    create table usuario (
       id bigint generated by default as identity,
        data_registro date,
        email varchar(255),
        login varchar(255),
        nome varchar(255),
        senha varchar(255),
        primary key (id)
    );

    create table usuario_perfil (
       usuario_id bigint not null,
        perfil_id bigint not null,
        primary key (usuario_id, perfil_id)
    );

    create table vaga (
       id bigint generated by default as identity,
        data_publicacao date,
        descricao varchar(255),
        salario_em_real double,
        status varchar(255),
        titulo varchar(255),
        categoria_id bigint,
        usuario_criador_id bigint,
        primary key (id)
    );

    alter table solicitacao 
       add constraint FK8yh0amq2bpaqivjkn0fo9209j 
       foreign key (arquivo_id) 
       references arquivo;

    alter table solicitacao 
       add constraint FKbe5pe9jd9857kk4jfpd89yoa9 
       foreign key (usuario_aplicante_id) 
       references usuario;

    alter table solicitacao 
       add constraint FKeo88bhwjbv2vehyt628aopft2 
       foreign key (vaga_id) 
       references vaga;

    alter table usuario_perfil 
       add constraint FK22cgfn0obntlvqyfn33pyk24d 
       foreign key (perfil_id) 
       references perfil;

    alter table usuario_perfil 
       add constraint FKnrjqnbylalt4ykxbcef24f57w 
       foreign key (usuario_id) 
       references usuario;

    alter table vaga 
       add constraint FKippstl3532kpapll4wmjejkk1 
       foreign key (categoria_id) 
       references categoria;

    alter table vaga 
       add constraint FK6up7q0pctw78tgh5dsv0epupf 
       foreign key (usuario_criador_id) 
       references usuario;

    create table arquivo (
       id bigint generated by default as identity,
        caminho varchar(255),
        nome varchar(255),
        tamanho varchar(255),
        tipo varchar(255),
        primary key (id)
    );

    create table categoria (
       id bigint generated by default as identity,
        descricao varchar(255),
        nome varchar(255),
        primary key (id)
    );

    create table perfil (
       id bigint generated by default as identity,
        descricao varchar(255),
        primary key (id)
    );

    create table solicitacao (
       id bigint generated by default as identity,
        comentario varchar(255),
        data_solicitacao date,
        arquivo_id bigint,
        usuario_aplicante_id bigint,
        vaga_id bigint,
        primary key (id)
    );

    create table usuario (
       id bigint generated by default as identity,
        data_registro date,
        email varchar(255),
        login varchar(255),
        nome varchar(255),
        senha varchar(255),
        primary key (id)
    );

    create table usuario_perfil (
       usuario_id bigint not null,
        perfil_id bigint not null,
        primary key (usuario_id, perfil_id)
    );

    create table vaga (
       id bigint generated by default as identity,
        data_publicacao date,
        descricao varchar(255),
        salario_em_real double,
        status varchar(255),
        titulo varchar(255),
        categoria_id bigint,
        usuario_criador_id bigint,
        primary key (id)
    );

    alter table solicitacao 
       add constraint FK8yh0amq2bpaqivjkn0fo9209j 
       foreign key (arquivo_id) 
       references arquivo;

    alter table solicitacao 
       add constraint FKbe5pe9jd9857kk4jfpd89yoa9 
       foreign key (usuario_aplicante_id) 
       references usuario;

    alter table solicitacao 
       add constraint FKeo88bhwjbv2vehyt628aopft2 
       foreign key (vaga_id) 
       references vaga;

    alter table usuario_perfil 
       add constraint FK22cgfn0obntlvqyfn33pyk24d 
       foreign key (perfil_id) 
       references perfil;

    alter table usuario_perfil 
       add constraint FKnrjqnbylalt4ykxbcef24f57w 
       foreign key (usuario_id) 
       references usuario;

    alter table vaga 
       add constraint FKippstl3532kpapll4wmjejkk1 
       foreign key (categoria_id) 
       references categoria;

    alter table vaga 
       add constraint FK6up7q0pctw78tgh5dsv0epupf 
       foreign key (usuario_criador_id) 
       references usuario;
